// <auto-generated/>

using System = global::System;

namespace Dagger.SDK.Client;

public partial class Dagger
{

}

public class Container
{
    public Container AsService() => throw new NotImplementedException();
    public Container AsTarball() => throw new NotImplementedException();
    public Container Build() => throw new NotImplementedException();
    public Container DefaultArgs() => throw new NotImplementedException();
    public Container Directory() => throw new NotImplementedException();
    public Container Entrypoint() => throw new NotImplementedException();
    public Container EnvVariable() => throw new NotImplementedException();
    public Container EnvVariables() => throw new NotImplementedException();
    public Container ExperimentalWithAllGPUs() => throw new NotImplementedException();
    public Container ExperimentalWithGPU() => throw new NotImplementedException();
    public Container Export() => throw new NotImplementedException();
    public Container ExposedPorts() => throw new NotImplementedException();
    public Container File() => throw new NotImplementedException();
    public Container From() => throw new NotImplementedException();
    public Container Id() => throw new NotImplementedException();
    public Container ImageRef() => throw new NotImplementedException();
    public Container Import() => throw new NotImplementedException();
    public Container Label() => throw new NotImplementedException();
    public Container Labels() => throw new NotImplementedException();
    public Container Mounts() => throw new NotImplementedException();
    public Container Pipeline() => throw new NotImplementedException();
    public Container Platform() => throw new NotImplementedException();
    public Container Publish() => throw new NotImplementedException();
    public Container Rootfs() => throw new NotImplementedException();
    public Container Stderr() => throw new NotImplementedException();
    public Container Stdout() => throw new NotImplementedException();
    public Container Sync() => throw new NotImplementedException();
    public Container Terminal() => throw new NotImplementedException();
    public Container User() => throw new NotImplementedException();
    public Container WithDefaultArgs() => throw new NotImplementedException();
    public Container WithDefaultTerminalCmd() => throw new NotImplementedException();
    public Container WithDirectory() => throw new NotImplementedException();
    public Container WithEntrypoint() => throw new NotImplementedException();
    public Container WithEnvVariable() => throw new NotImplementedException();
    public Container WithExec() => throw new NotImplementedException();
    public Container WithExposedPort() => throw new NotImplementedException();
    public Container WithFile() => throw new NotImplementedException();
    public Container WithFiles() => throw new NotImplementedException();
    public Container WithFocus() => throw new NotImplementedException();
    public Container WithLabel() => throw new NotImplementedException();
    public Container WithMountedCache() => throw new NotImplementedException();
    public Container WithMountedDirectory() => throw new NotImplementedException();
    public Container WithMountedFile() => throw new NotImplementedException();
    public Container WithMountedSecret() => throw new NotImplementedException();
    public Container WithMountedTemp() => throw new NotImplementedException();
    public Container WithNewFile() => throw new NotImplementedException();
    public Container WithRegistryAuth() => throw new NotImplementedException();
    public Container WithRootfs() => throw new NotImplementedException();
    public Container WithSecretVariable() => throw new NotImplementedException();
    public Container WithServiceBinding() => throw new NotImplementedException();
    public Container WithUnixSocket() => throw new NotImplementedException();
    public Container WithUser() => throw new NotImplementedException();
    public Container WithWorkdir() => throw new NotImplementedException();
    public Container WithoutDefaultArgs() => throw new NotImplementedException();
    public Container WithoutEntrypoint() => throw new NotImplementedException();
    public Container WithoutEnvVariable() => throw new NotImplementedException();
    public Container WithoutExposedPort() => throw new NotImplementedException();
    public Container WithoutFocus() => throw new NotImplementedException();
    public Container WithoutLabel() => throw new NotImplementedException();
    public Container WithoutMount() => throw new NotImplementedException();
    public Container WithoutRegistryAuth() => throw new NotImplementedException();
    public Container WithoutUnixSocket() => throw new NotImplementedException();
    public Container WithoutUser() => throw new NotImplementedException();
    public Container WithoutWorkdir() => throw new NotImplementedException();
    public Container Workdir() => throw new NotImplementedException();
}